name: SonarCloud Analysis

on:
  workflow_dispatch:
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  sonarcloud-analysis:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3

      # - name: Set up Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: 14

      - name: Install SonarScanner
        run: |
          npm install -g sonarqube-scanner
          sonar-scanner --version

      - name: Run SonarCloud analysis
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
