name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  sonarcloud-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install SonarScanner
        run: |
          npm install -g sonarqube-scanner
          sonar-scanner --version

      # - name: Configure SonarCloud properties
      #   run: |
      #     echo "sonar.host.url=https://sonarcloud.io" >> sonar-scanner-4.6.2.2472-linux/conf/sonar-scanner.properties
      #     echo "sonar.organization=thunsudamn" >> sonar-scanner-4.6.2.2472-linux/conf/sonar-scanner.properties
      #     echo "sonar.projectKey=thunsudamn" >> sonar-scanner-4.6.2.2472-linux/conf/sonar-scanner.properties
      #     echo "sonar.login=${{ secrets.SONARQUBE_TOKEN }}" >> sonar-scanner-4.6.2.2472-linux/conf/sonar-scanner.properties
      #     echo "sonar.sources=." >> sonar-scanner-4.6.2.2472-linux/conf/sonar-scanner.properties
      #     echo "sonar.language=js" >> sonar-scanner-4.6.2.2472-linux/conf/sonar-scanner.properties
      #     echo "sonar.exclusions=node_modules/**" >> sonar-scanner-4.6.2.2472-linux/conf/sonar-scanner.properties

      - name: Run SonarCloud analysis
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
