name: SonarCloud Analysis

on:
  workflow_dispatch:
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  sonarcloud-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          
      - name: Install dependencies
        run: |
          npm init -y
          echo "here 1"
          npm install jest --save-dev
          npm list jest
          echo "here 2"
          npm install --save-dev jest jest-sonar-reporter
          npm list jest-sonar-reporter
          echo "here 3"
          rm -rf node_modules
          rm package-lock.json
          npm install
          # npm update
          # yarn install
          # yarn upgrade
          # npx jest --clearCache
          npm run test:dev
          echo "here 4"

      - name: Run tests with coverage
        run: npm test -- --coverage --config=jest.config.js

      - name: SonarCloud scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

      # - name: Import coverage
      #   run: -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
